messages:
  message-format: '&4 %s'
  default-message: Tu ne peux pas faire cela
  modifyworld.items.use: Stop, &a$1&4 won't fit into &a$3
  modifyworld.login: Tu ne peux pas joindre ce serveur. Au revoir!
  modifyworld.blocks.interact: Tu es trop faible pour &2$1
  modifyworld.blocks.place: Tu ne peux pas placer &a$1
  modifyworld.blocks.destroy: '&a$1&4 est trop dur pour toi'
  modifyworld.damage.deal: Ton niveau est trop faible pour &5$1
  modifyworld.chat: Ta bouche est trop sèche
  modifyworld.chat.private: Impossible
  modifyworld.items.have: Item interdit &a$1&4 a été retiré de ton inventaire.
  modifyworld.items.drop: Il est interdit de jeter &a$1&4 par ici
  modifyworld.items.hold: Beware, &a$1&4 is cursed!
  modifyworld.items.craft: Désolé, mais &a$1&4 est trop compliqué
  modifyworld.items.enchant: Désolé, &a$1&4 est trop dangeureux
  modifyworld.vehicle.enter.boat: Tu es trop lourd pour &a$1
  modifyworld.vehicle.enter.minecart: Désolé, mais &a$1&4 est trop petit pour toi
  modifyworld.vehicle.destroy: Ce &a$1&4 est la propriété du serveur
  modifyworld.tame: Ce &a$1&4 est trop féroce
  modifyworld.bucket.fill: This bucket is holey
  modifyworld.bucket.empty: You suddenly realized you still need &a$1
  modifyworld.usebeds: You can't sleep yet, there are monsters nearby
